// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYnyWFlwdltthG7n5mgR4rZalLtVe0yRs',
    appId: '1:215666210709:web:9dff82c335236f4b0e689c',
    messagingSenderId: '215666210709',
    projectId: 'darb-42eca',
    authDomain: 'darb-42eca.firebaseapp.com',
    storageBucket: 'darb-42eca.firebasestorage.app',
    measurementId: 'G-JQWT27106Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHeEK90DQsBwrs9Hmep7cqkBv6Gl9G9d0',
    appId: '1:215666210709:android:b8329ab710fdbde80e689c',
    messagingSenderId: '215666210709',
    projectId: 'darb-42eca',
    storageBucket: 'darb-42eca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx3S6kVHXl2Y73caJXZkWrOH324AWIHFo',
    appId: '1:215666210709:ios:3bb6b2f16181923c0e689c',
    messagingSenderId: '215666210709',
    projectId: 'darb-42eca',
    storageBucket: 'darb-42eca.firebasestorage.app',
    iosBundleId: 'com.example.darb',
  );
}
